import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";
import QuerysProvider from "./QuerysProvider";
import { SessionProvider } from "next-auth/react";
import { ReduxProvider } from "./ReduxProviders";

const QuickSand = Quicksand({
  variable: "--font-QuickSand",
  subsets: ["latin"],
  weight: ["400", "700"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" data-theme="light">
      <body className={`${QuickSand.variable}  antialiased`}>
        <SessionProvider>
          <QuerysProvider>
            <ReduxProvider>{children}</ReduxProvider>
          </QuerysProvider>
        </SessionProvider>
      </body>
    </html>
  );
}
